
spring:
  application:
    name: entrance
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: myuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 8081
